version: '3.8'
services:
  sync:
    build: .
    environment:
      AIRBASE_API_KEY: ${AIRBASE_API_KEY}
      MERC_API_USER: ${MERC_API_USER}
      MERC_API_TOKEN: ${MERC_API_TOKEN}
    volumes:
      - ./auth.json:/config/auth.json
      - ./cache.db:/config/cache.db
    restart: always